# TODO - take the instances below and pass them through the frame and adjust,
#        then translate the sequences and see if they remain in reading frame
#        goal is to determine if the different models will required different
#        starting points for correct translation
#      - add the aa_check params to the pipleline function.

# DONE - translation using the correct table is completed.
#      - conducting the indel check.
#      - on the three I tried, the sequences are being set in the common reading frame 
#        (i.e. 1st bp is the first position in the first codon)


#' trans1 which is archaeognatha is in proper reading frame

test_that("Sequences are translated and checked for amino acids correctly.", {

###########################################3
# test of trans set 4
#consensus should be:
	
  #PACBB051-16
	#------------------------------------------------TTTATTTTTGGAATTTGAGCTGGAATAGTAGGAACTTCCTTA---AGATTATTAATTCGATTAGAATTAAGAACTATTAAAAATTTAATTGGAAAC---GATCAAATTTATAATGTAATTGTAACTGCTCATGCTTTTATTATAATTTTTTTTATAGTTATACCAATTTTAATTGGGGGATTTGGAAATTGATTAATTCCTATTATA---TTAGGAGCACCAGATATAGCTTTTCCACGAATAAACAATATAAGATTTTGAATATTGCCCCCTTCTTTATCTTTATTATTAATTAGAAGAATAGTTGAAACTGGGACTGGAACAGGATGAACAGTCTATCCTCCTCTATCTTCAGTAATCGCCCACACAGGTTCATCAGTTGATTTTTCT---ATTTTTTCTTTACATATTGCAGGAATTTCTTCTATTTTAGGAGCAATTAATTTTATTTCAACAATAATAAATATAAAAATTAAATTTTTAAAATTTAATCAAATTTCATTATTTATTTGATCTATTTTAATTACTACAATTTTATTATTATTATCATTACCAGTATTAGCCGGA---GCTATTACTATATTATTAACAGATCGA----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	#----------------FIFGIWAGMVGTSL-SLLIRLELSTIKNLIGN-DQIYNVIVTAHAFIMIFFMVMPILIGGFGNWLIPIM-LGAPDMAFPRMNNMSFWMLPPSLSLLLISSMVETGTGTGWTVYPPLSSVIAHTGSSVDFS-IFSLHIAGISSILGAINFISTMMNMKIKFLKFNQISLFIWSILITTILLLLSLPVLAG-AITMLLTDR---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

	nucraw = 'TTTATTTTTGGAATTTGAGCTGGAATAGTAGGAACTTCCTTAAGATTATTAATTCGATTAGAATTAAGAACTATTAAAAATTTAATTGGAAACGATCAAATTTATAATGTAATTGTAACTGCTCATGCTTTTATTATAATTTTTTTTATAGTTATACCAATTTTAATTGGGGGATTTGGAAATTGATTAATTCCTATTATATTAGGAGCACCAGATATAGCTTTTCCACGAATAAACAATATAAGATTTTGAATATTGCCCCCTTCTTTATCTTTATTATTAATTAGAAGAATAGTTGAAACTGGGACTGGAACAGGATGAACAGTCTATCCTCCTCTATCTTCAGTAATCGCCCACACAGGTTCATCAGTTGATTTTTCTATTTTTTCTTTACATATTGCAGGAATTTCTTCTATTTTAGGAGCAATTAATTTTATTTCAACAATAATAAATATAAAAATTAAATTTTTAAAATTTAATCAAATTTCATTATTTATTTGATCTATTTTAATTACTACAATTTTATTATTATTATCATTACCAGTATTAGCCGGAGCTATTACTATATTATTAACAGATCGA'
	expected_consensus = 'ACATTATATTTTATTTTTGGAATTTGAGCTGGAATAGTAGGAACTTCCTTAAGATTATTAATTCGATTAGAATTAAGAACTATTAAAAATTTAATTGGAAACGATCAAATTTATAATGTAATTGTAACTGCTCATGCTTTTATTATAATTTTTTTTATAGTTATACCAATTTTAATTGGGGGATTTGGAAATTGATTAATTCCTATTATATTAGGAGCACCAGATATAGCTTTTCCACGAATAAACAATATAAGATTTTGAATATTGCCCCCTTCTTTATCTTTATTATTAATTAGAAGAATAGTTGAAACTGGGACTGGAACAGGATGAACAGTCTATCCTCCTCTATCTTCAGTAATCGCCCACACAGGTTCATCAGTTGATTTTTCTATTTTTTCTTTACATATTGCAGGAATTTCTTCTATTTTAGGAGCAATTAATTTTATTTCAACAATAATAAATATAAAAATTAAATTTTTAAAATTTAATCAAATTTCATTATTTATTTGATCTATTTTAATTACTACAATTTTATTATTATTATCATTACCAGTATTAGCCGGAGCTATTACTATATTATTAACAGATCGAAATTTAAATACATCATTTTTTGATCCTATAGGAGGAGGAGACCCAATTCTTTATCAACATTT'

	trans_sequences = list(
		'ATTCAACCAATCATAAAGATATTGGAACATTATATTTTATTTTTGGAATTTGAGCTGGAATAGTAGGAACTTCCTGAAGATTATTAATTCGATTAGAATTAAGAACTATTAAAAATTTAATTGGAAACGATCAAATTTATAATGTAATTGTAACTGCTCATGCTTTTATTATAATTTTTTTTATAGTTATACCAATTTTAATTGGGGGATTTGGAAATTGATTAATTCCTATTATATTAGGAGCACCAGATATAGCTTTTCCACGAATAAACAATATAAGATTTTGAATATTGCCCCCTTCTTTATCTTTATTATTAATTAGAAGAATAGTTGAAACTGGGACTGGAACAGGATGAACAGTCTATCCTCCTCTATCTTCAGTAATCGCCCACACAGGTTCATCAGTTGATTTTTCTATTTTTTCTTTACATATTGCAGGAATTTCTTCTATTTTAGGAGCAATTAATTTTATTTCAACAATAATAAATATAAAAATTAAATTTTTAAAATTTAATCAAATTTCATTATTTATTTGATCTATTTTAATTACTACAATTTTATTATTATTATCATTACCAGTATTAGCCGGAGCTATTACTATATTATTAACAGATCGAAATTTAAATACATCATTTTTTGATCCTATAGGAGGAGGAGACCCAATTCTTTATCAACATTTATTTTGATTTTTTGGTACATCCAGAAGTTTA',
		'GGTCAACAAATCATAAAGATATTGGAACATTATATTTTATTTTTGGAATTTGAGCTGGAATAGTAGGAACTTCCTTAAGATTACTAATTCGATTAGAATTAAGAACTATTAAAAATTTAATTGGAAACGATCAAATTTATAATGTAATTGTAACTGCTCATGCTTTTATTATAATTTTTTTTATAGTTATACCAATTTTAATTGGGGGATTTGGAAATTGATTAATTCCTATTATATTAGGAGCACCAGATATAGCTTTTCCACGAATAAACAATATAAGATTTTGAATATTGCCCCCTTCTTTATCTTTATTATTAATTAGAAGAATAGTTGAAACTGGGACTGGAACAGGATGAACAGTCTATCCTCCTCTATCTTCAGTAATCGCCCACACAGGTTCATCAGTTGATTTTTCTATTTTTTCTTTACATATTGCAGGAATTTCTTCTATTTTAGGAGCAATTAATTTTATTTCAACAATAATAAATATAAAAATTAAATTTTTAAAATTTAATCAAATTTCATTATTTATTTGATCTATTTTAATTACTACAATTTTATTATTATTATCATTACCAGTATTAGCCGGAGCTATTACTATATTATTAACAGATCGAAATTTAAATACATCATTTTTTGATCCTATAGGAGGAGGAGACCCAATTCTTTATCAACATTTATTTTGATTTTTTGGACATCCATGAAGTTT',
		'AGTCAACAAATCATAAAGATATTGGAACATTATATTTTATTTTTGGAATTTGAGCTGGAATAGTAGGAACTTCCTTAAGATTATTAATTCGATTAGAATTAAGAACTATTAAAAATTTAATTGGAAACGATCAAATTTATAATGTAATTGTAACTGCTCATGCTTTTATTATAATTTTTTTTATAGTTATACCAATTTTAATTGGGGGGATTTGGAAATTGATTAATTCCTATTATATTAGGAGCACCAGATATAGCTTTTCCACGAATAAACAATATAAGATTTTGAATATTGCCCCCTTCTTTATCTTTATTATTAATTAGAAGAATAGTTGAAACTGGGACTGGAACAGGATGAACAGTCTATCCTCCTCTATCTTCAGTAATCGCCCACACAGGTTCATCAGTTGATTTTTCTATTTTTTCTTTACATATTGCAGGAATTTCTTCTATTTTAGGAGCAATTAATTTTATTTCAACAATAATAAATATAAAAATTAAATTTTTAAAATTTAATCAAATTTCATTATTTATTTGATCTATTTTAATTACTACAATTTTATTATTATTATCATTACCAGTATTAGCCGGAGCTATTACTATATTATTAACAGATCGAAATTTAAATACATCATTTTTTGATCCTATAGGAGGAGGAGACCCAATTCTTTATCAACATTTATTTTGATTTTTTGGTACACCCTGAAGTTTA',
		'GGTCAACCAATCATAAAGATATTGGAACATTATATTTTATTTTTGGAGTTTGAGCTGGAATAGTAGGAACTTCCTTAAGATTATTAATTCGATTAGAATTAAGAACTATTAAAAATTTAATTGGAAACGATCAAATTTATAATGTAATTGTAACTGCTCATGCTTTTATTATAATTTTTTTTATAGTTATACCAATTTTAATTGGGGGATTTGGAAATTGATTAATTCCTATTATATTAGGAGCACCAGATATAGCTTTTCCACGAATAAACAATATAAGATTTTGAATATTGCCCCCTTCTTTATCTTTATTATTAATTAGAAGAATAGTTGAAACTGGGACTGGAACAGGATGAACAGTCTATCCTCCTCTATCTTCAGTAATCGCCCACACAGGTTCATCAGTTGATTTTTCTATTTTTTCTTTACATATTGCAGGAATTTCTTCTATTTTAGGAGCAATTAATTTTATTTCAACAATAATAAATATAAAAATTAAATTTTTAAAATTTAATCAAATTTCATTATTTATTTGATCTATTTTAATTACTACAATTTTATTATTATTATCATTACCAGTATTAGCCGGAGCTATTACTATATTATTAACAGATCGAAATTTAAATACATCATTTTTTGATCCTATAGGAGGAGGAGACCCAATTCTTTATCAACATTTATTTTGATTTTTTGGACATCCAGAAGTTTA'
		)

	trans_ccs	= build_ccs(x = trans_sequences,
							id = 'PACBB051-16', 
							order = 'diptera')	


	trans_ccs = frame(trans_ccs)
	trans_ccs = adjust(trans_ccs)

	trans_ccs = consensus(trans_ccs)
	trans_ccs = aa_check(trans_ccs, trans_table= 5)
	
	#trans_ccs$consensus == expected_consensus
	expect_equal(trans_ccs$consensus, expected_consensus)
	expect_equal(trans_ccs$stop_codons, FALSE)

	err_consensus = 'ACATTATATTTTATTTTTGGAATTTGAGCTGGAATTAGTAGGAACTTTCCTTAAGATTATTAATTCGATTAGAATTAAGAACTATTAAAAATTTAATTGGAAACGATCAAATTTATAATGTAATTGTAACTGCTCATGCTTTTATTATAATTTTTTTTATAGTTATACCAATTTTAATTGGGGGATTTGGAAATTGATTAATTCCTATTATATTAGGAGCACCAGATATAGCTTTTCCACGAATAAACAATATAAGATTTTGAATATTGCCCCCTTCTTTATCTTTATTATTAATTAGAAGAATAGTTGAAACTGGGACTGGAACAGGATGAACAGTCTATCCTCCTCTATCTTCAGTAATCGCCCACACAGGTTCATCAGTTGATTTTTCTATTTTTTCTTTACATATTGCAGGAATTTCTTCTATTTTAGGAGCAATTAATTTTATTTCAACAATAATAAATATAAAAATTAAATTTTTAAAATTTAATCAAATTTCATTATTTATTTGATCTATTTTAATTACTACAATTTTATTATTATTATCATTACCAGTATTAGCCGGAGCTATTACTATATTATTAACAGATCGAAATTTAAATACATCATTTTTTGATCCTATAGGAGGAGGAGACCCAATTCTTTATCAACATTT'
	after_mask = "ACATTATATTTTATTTTTGGAATTTGAGCTGGAATTAGTAGGAACTTTCCTTANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"

	trans_ccs$consensus = err_consensus
	trans_ccs = aa_check(trans_ccs, trans_table= 5)
	

	expect_equal(trans_ccs$stop_codons, TRUE)
	expect_equal(trans_ccs$consensus, after_mask)
})

