test_that("Artifical errors are denoised properly.", {
    
  #PACBB5941-16
  toy_example1 ='ACAATGTATTTCATCCTAGGAATATGATCAGGAATATTAGGAATAATATTAAGAATATTATTCGAATTGAACTAGCACAACCAGGACCATTAATAAGAAATGACCAAATTTATAATGTAATTGTTACATCTCATGCATTCATTATAATTTTTATGGTAATACCAATTATAATCGGAGGATTCGGAAATTGATTAGTACCATTAATAATTGGAGCACCAGATATAGCATTCCCACGAATAAATAATATAAGATTTTGACTTCTTCCACCCTCACTTACATTGTTAATTTCAAGATCAATAGTAGAAATAGGACCAGGAACAGGATGAACACTATATCCACCGCTATCGTCAAATATTGCACATTCGGGAGGAAGTGTAGACTTAAGAATTTTTTCATTACACTTAGCCGGTGTATCATCAATCCTAGGAGCAATTAACTTTATTACAACAATTCTAAATATACGAACACTAGGAATATCATTAGACCGAACCCCCTTATTCGTATGATCAGTAATAATTACTGCAATTTTACTACTTCTATCTCTACCAGTACTAGCTGGAGCAATCACGATA'
  	
  
  toy1_expected = ""
  
  test_toy1_out = denoise(toy_example1, 
                          name = "example1",
                      		ambig_char = "N",
                      		censor_length = 3,
                      		aa_check = FALSE, 
                      		to_file = FALSE)
  
  test_toy1_out$adjusted_sequence
  #TODO - make this operational
  #expect_equal(test_toy1_out$consensus, toy1_expected)
    
  #PACBB858-16
  #567 length sequence and it has the starting point that seems to be causing the issue with alignment
  toy_example2 = 'TTTTTGGTGCATGATCTAGAATAGTAGGAACTTCCTTAAGAATATTAATTCGTGCAGAATTAGGAACCCCTAATGCATTAATTGGAGATGATCAAATTTATAATGTAATTGTAACAGCCCATGCATTCATTATAATTTTCTTTATAGTAATACCTATTATAATTGGAGGATTTGGTAATTGATTAGTACCACTGATATTAAGAGCCCCTGATATAGCTTTCCACGATTAAATAATATAAGATTTTGACTTTTACCTCCATCTTTAACATTATTGTTAACTAGAAGTTTAGTAGAAAGAGGAACCGGTACAGGATGAACAGTTTACCCCCCACTGTCATCTACATTAAGGCATTCCGGAGCATCTGTAGATTTATCTATTTTTTCTTTGCATTTAGCAGGGATTTCCTCTATTCTAGGAGCAGTAAATTTTATTTCAACAATTATTAATATACGGGCCCCAGGAATAACTTTTGATAAAATACCTTTATTTGTGTGATCAGTATTAATTACTGCAGTATTACTATTATTATCTTTACCAGTTCTAGCTGGAGCAATTACTATA'

  
  toy2_expected = ""
  
  
  test_toy2_out = denoise(x = toy_example2,
  						            name = "toy_example2-short_and_messy",
                      		ambig_char = "N",
                      		censor_length = 3,
                      		aa_check = FALSE, 
                      		to_file = FALSE)
  
  #TODO - make this operational
  #expect_equal(test_toy2_out$consensus, toy2_expected)
  
  toy_example3 = 'ACACTTTACTTTATTTTTGGTATTTGAGCAGGTATATTAGGGACTTCATTAAGTTTATTAATTCGAGCAGAAATTAGGTAATCCAGGTTCTTTAATTGGAGATGATCAAATTTATAATACTATTGTTACAGCTCATGCTTTTATTATAATTTTTTTTATAGTTATGCCAATTATAATTGGAGGTTTTGGTAATTGACTAGTTCCTTTAATACTAGGAGCCCCTGATATAGCTTTCCCCCGAATAAATAATATAAGTTTCTGACTTTTACCTCCCTCTCTTACCTTATTAATTTCAAGAAGAATTGTAGAAAATGGTGCAGGAACTGGATGAACAGTTTACCCTCCTCTTTCTTCTAATATCGCTCATAGAGGAAGATCAGTAGATTTAGCTATTTTTTCTTTACATTTAGCTGGTATTTCATCAATTTTAGGGGCTATTAATTTTATTACTACAATTATTAACATACGATTAAATAGACTAATATTTGATCAAATACCTTTATTCGTATGAGCTGTAGGGATTACTGCTTTTCTTTTA'
  
  toy3_expected = ""
  
  test_toy3_out = denoise(x = toy_example3,
                          name = "toy_example3-long_and_messy",
                          ambig_char = "N",
                          censor_length = 3,
                          aa_check = FALSE, 
                          to_file = FALSE)
  
  #TODO - make this operational
  #expect_equal(test_toy3_out$consensus, toy3_expected)
  
  

  expect_equal(1,1)
})


