
test_that("The adjustment of individual ccs reads is conducted properly.", {

  #TODO - add test1 here that looks at sequences with leading dashes... these can break the censorship logic
  
  
  ############################
	order2 = 'lepidoptera'
	starting_sequence2 = 'TTTATTTTTGGAATTTGATCCGGAATAATTGGAACATCTCTTAGTCTATTAATTCGTGCTGAATTAGGAAACCCAGGCTCTTTAATTGGAGATGATCAAATTTATAATACAATTGTTACCGCCCACGCCTTTATTATAATTTTTTTCATGGTTATACCAATTATAATTGGAGGATTTGGAAATTGATTAGTACCTTTAATATTAGGAGCTCCTGATATAGCTTTCCCCCGAATAAATAATATAAGATTTTGATTACTTCCCCCTTCACTTACTTTATTAGTTTCTAGAAGAATTGTAGAAAATGGAGTAGGAACAGGATGAACAGTATACCCCCCTTTATCTTCTAATATTGCCCATGGTGGAGGCTCTGTTGATTTAGCAATCTTTTCTCTTCATTTAGCTGGAATTTCTTCAATTTTAGGAGCTGTCAATTTTATTACAACAGTAATTAATATACGAACAAATGGTATATCTTTTGATCGAATACCATTATTTGTTTGATCTGTTGCTATCACAGCACTTCTACTACTTTTATCTTTACCTGTCTTAGCTGGAGCTATTACTATACTTTTAACTGAT'


	#pull the correct components from this
	fake_ccs_data2 = list(
	'TTTATTTTTGGAATTTGATCCGGAATAATTGGAACATCTCTTAGTCTATTAATTCGTGCTGAATTAGGAAACCCAGGCTCTTTAATTGGAGATGATCAAATTTATAATACAATTGTTACCGCCCACGCCTTTATTATAATTTTTTTCATGGTTATACCAATTATAATTGGAGGATTTGGAAATTGATTAGTACCTTTAATATTAGGAGCTCCTGATATAGCTTTCCCCCGAATAAATAATATAAGATTTTGATTACTTCCCCCCTTCACTTACTTTATTAGTTTCTAGAAGAATTGTAGAAAATGGAGTAGGAACAGGATGAACAGTATACCCCCCTTTATCTTCTAATATTGCCCATGGTGGAGGCTCTGTTGATTTAGCAATCTTTTCTCTTCATTTAGCTGGAATTTCTTCAATTTTAGGAGCTGTCAATTTTATTACAACAGTAATTAATATACGAACAAATGGTATATCTTTTGATCGAATACCATTATTTGTTTGATCTGTTGCTATCACAGCACTTCTACTACTTTTATCTTTACCTGTCTTAGCTGGAGCTATTACTATACTTTTAACTGAT',
	'TTTATTTTTGGAATTTGATCCGGAATAATTGGAACATCTCTTAGTCTATTAATTCGTGCTGAATTAGGAAACCCAGGCTCTTTAATTGGAGATGATCAAATTTATAATACAATTGTTACCGCCCACGCCTTTATTATAATTTTTTTCATGGTTATACCAATTATAATTGGAGGATTTGGAAATTGATTAGTACCTTTAATATTAGGAGCTCCTGATATAGCTTTCCCCCGAATAAATAATATAAGATTTTGATTACTTCCCCCTTCACTTACTTTATTAGTTTCTAGAAGAATTGTAGAAAATGGAGTAGGAACAGGATGAACAGTATACCCCCCTTTATCTTCTAATATTGCCCATGGTGGAGGCTCTGTTGATTTAGCAATCTTTTCTCTTCATTTAGCTGGAATTTCTTCAATTTTAGGAGCTGTCAATTTTATTACAACAGTAATTAATATACGAACAAATGGTATATCTTTTGATCGAATACCATTATTTGTT',
	'TTTATTTTTGGAATTTGATCCGGAATAATTGGAACATCTCTTAGTCTATTAATTCGTGCTGAATTAGGAAACCCAGGCTCTTTAATTGGAGATGATCAAATTTATAATACAATTGTTACCGCCCACGCCTTTATTATAATTTTTTTCATGGTTATACCAATTATAATTGGAGGATTTGGAAATTGATTAGTACCTTTAATATTAGGAGCTCCTGATATAGCTTTCCCCCCGAATAAATAATATAAGATTTTGATTACTTCCCCCTTCACTTACTTTATTAGTTTCTAGAAGAATTGTAGAAAATGGAGTAGGAACAGGATGAACAGTATACCCCCCTTTATCTTCTAATATTGCCCATGGTGGAGGCTCTGTTGATTTAGCAATCTTTTCTCTTCATTTAGCTGGAATTTCTTCAATTTTAGGAGCTGTCAATTTTATTACAACAGTAATTAATATACGAACAAATGGTATATCTTTTGATCGAATACCATTATTTGTTTGATCTGTTGCTATCACAGCACTTCTACTACTTTTATCTTTACCTGTCTTAGCTGGAGCTATTACTATACTTTTAACTGAT'
		)

	fake_ccs_2 = build_ccs(x = fake_ccs_data2,
							id = "Fake indel ccs test 2", 
							order = order2)	


	fake_ccs_2 = frame(fake_ccs_2)
	fake_ccs_2 = adjust(fake_ccs_2)
	
	fake_ccs_2 = consensus(fake_ccs_2)

	#NOTE: these are based on looking at the paths built from aphid and seeing where the corrections
	#should be applied and where certainty in the sequence drops off.
	read_1_output = "---------tttatttttggaatttgatccggaataattggaacatctcttagtctattaattcgtgctgaattaggaaacccaggctctttaattggagatgatcaaatttataatacaattgttaccgcccacgcctttattataatttttttcatggttataccaattataattggaggatttggaaattgattagtacctttaatattaggagctcctgatatagctttcccccgaataaataatataagattttgattacttccc------cttactttattagtttctagaagaattgtagaaaatggagtaggaacaggatgaacagtatacccccctttatcttctaatattgcccatggtggaggctctgttgatttagcaatcttttctcttcatttagctggaatttcttcaattttaggagctgtcaattttattacaacagtaattaatatacgaacaaatggtatatcttttgatcgaataccattatttgtttgatctgttgctatcacagcacttctactacttttatctttacctgtcttagctggagctattactatacttttaa"
	read_2_output = "---------tttatttttggaatttgatccggaataattggaacatctcttagtctattaattcgtgctgaattaggaaacccaggctctttaattggagatgatcaaatttataatacaattgttaccgcccacgcctttattataatttttttcatggttataccaattataattggaggatttggaaattgattagtacctttaatattaggagctcctgatatagctttcccccgaataaataatataagattttgattacttcccccttcacttactttattagtttctagaagaattgtagaaaatggagtaggaacaggatgaacagtatacccccctttatcttctaatattgcccatggtggaggctctgttgatttagcaatcttttctcttcatttagctggaatttcttcaattttaggagctgtcaattttattacaacagtaattaatatacgaacaaatggtatatcttttga"
	read_3_output = "---------tttatttttggaatttgatccggaataattggaacatctcttagtctattaattcgtgctgaattaggaaacccaggctctttaattggagatgatcaaatttataatacaattgttaccgcccacgcctttattataatttttttcatggttataccaattataattggaggatttggaaattgattagtacctttaatattaggagctcctgatatagctttc------ataaataatataagattttgattacttcccccttcacttactttattagtttctagaagaattgtagaaaatggagtaggaacaggatgaacagtatacccccctttatcttctaatattgcccatggtggaggctctgttgatttagcaatcttttctcttcatttagctggaatttcttcaattttaggagctgtcaattttattacaacagtaattaatatacgaacaaatggtatatcttttgatcgaataccattatttgtttgatctgttgctatcacagcacttctactacttttatctttacctgtcttagctggagctattactatacttttaa"

	#note the alignment of the first read is fickle... need to fix this test!
	#fake_ccs_2$consensus == consensus2_sequence_expected
	expect_equal(paste(fake_ccs_2$adjusted_sequences[[1]],collapse=''), read_1_output)
	expect_equal(paste(fake_ccs_2$adjusted_sequences[[2]],collapse=''), read_2_output)
	expect_equal(paste(fake_ccs_2$adjusted_sequences[[3]],collapse=''), read_3_output)

})